name: Lint

on: [push]

jobs:
  lint:
    runs-on: windows-latest
    name: ESLint checker

    strategy:
      matrix:
        node-version: ['12.*']

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm install
        run: npm ci --ignore-scripts 
      
      - name: Install Eslint
        run: npm install eslint 
            
      - name: run eslint
        run: eslint src/components/*.vue

